env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
plugins:
  - mocha
rules:
  indent: [error, 2, SwitchCase: 1]
  linebreak-style: [error, unix]
  semi: [error, always]
  no-console: off
  eqeqeq: [error, always]
  mocha/no-exclusive-tests: error
